apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-backend-inmobiliaria-kevin-inofuente
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/datapath-kevin-inofuentecolque/repositorio-backend-langchain-inmobiliaria/imagen-v2-backend-langchain-inmobiliaria-k:latest
          ports:
            - containerPort: 4000
